<?php
/**
 * Created by Mota-systems company.
 * Author: Pavel Lamzin
 * Date: 04.02.2016
 * Time: 3:53
 * All rights are reserved
 */
namespace app\components;

use Yii;
use yii\filters\AccessRule;
use yii\helpers\VarDumper;

class CustomAccessRule extends AccessRule {

	protected function matchRole($user) {
		if (empty($this->roles)) {
			return TRUE;
		}
		foreach ($this->roles as $role) {
			if ($role === '?') {
				if ($user->getIsGuest()) {
					return TRUE;
				}
			} elseif ($role === '@') {
				if (!$user->getIsGuest()) {
					return TRUE;
				}
			} elseif (is_array($role)) {
				list($role, $params) = $role;
				if ($user->can($role, $params)) {
					return TRUE;
				}
			} elseif ($user->can($role)) {
				return TRUE;
			}
		}

		return FALSE;
	}

	public function allows($action, $user, $request) {
		$result = parent::allows($action, $user, $request); // TODO: Change the autogenerated stub
		Yii::info(VarDumper::dumpAsString($user));
		Yii::info(VarDumper::dumpAsString($request));

		return $result;
	}

}